# Generated by Django 4.2.2 on 2023-06-18 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_remove_user_is_active_remove_user_is_staff_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
